apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: island10
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/vadossam/appset-playground.git'
      revision: master
      files:
      - path: apps/**/overlays/island10/config.json
      template:
        metadata:
          name: '{{ path[2] }}-island10'
          namespace: argocd
        spec:
          destination:
            server: '{{ destServer }}'
            namespace: default
          project: default
          source:
            repoURL: 'https://github.com/vadossam/appset-playground.git'
            path: '{{ srcPath }}'
  - git:
      repoURL: 'https://github.com/vadossam/appset-playground.git'
      revision: master
      directories:
      - path: apps/generic/*
      - path: apps/overcloud/*

  template:
    metadata:
      name: '{{ path.basename }}-island10'
      namespace: argocd
    spec:
      destination:
        namespace: default
        server: '{{ destServer }}'
      project: default
      source:
        path: '{{ path }}'
        repoURL: 'https://github.com/vadossam/appset-playground.git'
        targetRevision: master
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
