apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: logging-operator
name: logging-operator
releaseName: logging-operator
repo:  https://kubernetes-charts.banzaicloud.com
version: 3.17.7
valuesFile: values.yaml
namespace: logging-operator
valuesInline:
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
