apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: docker.io/kostiscodefresh/simple-web-app
  newName: docker.io/kostiscodefresh/simple-web-app
  newTag: c88df35
