apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  version: 1.7.0
  repo: https://charts.jetstack.io
  namespace: cert-manager
  releaseName: cert-manager
  valuesInline:
    installCRDs: true
