apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager-ns.yaml

helmCharts:
- name: cert-manager
  version: 1.8.2
  repo: https://charts.jetstack.io
  namespace: cert-manager
  releaseName: cert-manager
  valuesInline:
    installCRDs: true
