apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmChartInflationGenerator:
- chartName: cert-manager
  chartRepoUrl: https://charts.jetstack.io
  chartVersion: 1.7.0
  releaseName: cert-manager
  namespace: cert-manager
  #values: values.yaml
  valuesLocal:
    installCRDs: true
  # valuesMerge specifies how to treat valuesLocal with respect to Values.
  # Legal values: 'merge', 'override', 'replace'.
  # Defaults to 'override'.
