apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: logging-operator
name: logging-operator
releaseName: logging-operator
values: values.yaml
repo:  https://kubernetes-charts.banzaicloud.com
version: 3.17.7
namespace: cattle-logging-system
