apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: logging-operator
name: logging-operator
releaseName: logging-operator
repo:  https://kubernetes-charts.banzaicloud.com
version: 3.17.7
values: values.yaml
valuesInline:
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
