apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmChartInflationGenerator:
- chartName: logging-operator
  chartRepoUrl: https://kubernetes-charts.banzaicloud.com
  chartVersion: 3.17.7
  releaseName: logging-operator
  # override with these custom values
  values: values.yaml
