apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#resources:
#  - chart.yaml
#generators:
#  - chart.yaml

helmChartInflationGenerator:
- chartName: cert-manager
  chartRepoUrl: https://charts.jetstack.io
  chartVersion: 1.7.0
  values: values.yaml
  valuesLocal:
    replicaCount: 2
  # valuesMerge specifies how to treat valuesLocal with respect to Values.
  # Legal values: 'merge', 'override', 'replace'.
  # Defaults to 'override'.
