apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#resources:
#  - chart.yaml
#generators:
#  - chart.yaml

helmChartInflationGenerator:
- chartName: cert-manager
  chartRepoUrl: https://charts.jetstack.io
  chartVersion: 1.7.0
  releaseName: logging-operator
  # override with these custom values
  values: values.yaml
  valuesLocal:
    replicaCount: 2
